// ═══════════════════════════════════════════════
// YAYO — Demo listings (shared by all pages)
// Shown until real dealer inventory exists.
// ═══════════════════════════════════════════════
// Demo shipping agencies (only shown on demo listings, clearly labeled)
window.YAYO_DEMO_AGENCIES = [
  { id: "ag-demo-1", name: "TransAfrica Cargo (démo)", verified: true,
    meta: { years: 8, languages: "Français, English",
      description: "Spécialiste du transport de véhicules Dubai → Afrique centrale et de l'Ouest. RoRo et conteneur, dédouanement assisté. (Agence de démonstration)",
      pickup: "Warehouse 12, Ras Al Khor Industrial 2, Dubai",
      offices: { kinshasa: "12 Av. du Commerce, Gombe, Kinshasa", douala: "Rue Joffre, Akwa, Douala", dakar: "Km 4, Route de Rufisque, Dakar" } },
    routes: [
      { city: "kinshasa", price: 3150, days: 32, promise: "Je livre votre voiture à Kinshasa en 32 jours" },
      { city: "douala", price: 2750, days: 27, promise: "Douala en 27 jours, port-à-port" },
      { city: "dakar", price: 3250, days: 30, promise: "Dakar en 30 jours, assurance incluse" }] },
  { id: "ag-demo-2", name: "Gulf-Africa Shipping (démo)", verified: true,
    meta: { years: 5, languages: "English, العربية",
      description: "Liaisons rapides Dubai → Kinshasa et Abidjan, départs chaque semaine. (Agence de démonstration)",
      pickup: "Al Quoz Industrial 3, Dubai",
      offices: { kinshasa: "Blvd du 30 Juin, Kinshasa", abidjan: "Zone portuaire, Treichville, Abidjan" } },
    routes: [
      { city: "kinshasa", price: 3350, days: 25, promise: "Kinshasa en 25 jours, le plus rapide" },
      { city: "abidjan", price: 3400, days: 33, promise: "Abidjan en 33 jours, dédouanement assisté" }] }
];

window.YAYO_DEMO = [
  { id: "demo-1",  car_name: "Toyota Land Cruiser GXR 2021", year: 2021, mileage: 78000,  fuel: "Essence",    body: "SUV",     color: "Blanc perle",  condition: "Excellent état", price: 38500, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Toyota_Land_Cruiser_300_4x4_ZX_2025_%281%29.jpg/960px-Toyota_Land_Cruiser_300_4x4_ZX_2025_%281%29.jpg", description: "Land Cruiser GXR V6, entretien complet chez Toyota Dubai, jamais accidenté. Parfait pour les routes africaines : fiable, spacieux, pièces disponibles partout.", dealer: { name: "Mukoma Auto", verified: true } },
  { id: "demo-2",  car_name: "Toyota RAV4 Hybrid 2022",      year: 2022, mileage: 41000,  fuel: "Hybride",    body: "SUV",     color: "Gris anthracite", condition: "Comme neuf", price: 27900, ai: "nego", photo_url: "https://images.unsplash.com/photo-1706509234538-9831b1b33d66?w=640&q=70", description: "RAV4 Hybrid, consommation très basse (5L/100km), idéal ville + route. Batterie sous garantie constructeur.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-3",  car_name: "Toyota Hilux 4x4 2020",        year: 2020, mileage: 96000,  fuel: "Diesel",     body: "Pick-up", color: "Blanc",        condition: "Très bon état", price: 31200, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Toyota_Hilux_2024_%2848021%29.jpg/960px-Toyota_Hilux_2024_%2848021%29.jpg", description: "Hilux double cabine 4x4 diesel, le pick-up le plus demandé d'Afrique. Châssis inspecté, benne d'origine.", dealer: { name: "Mukoma Auto", verified: true } },
  { id: "demo-4",  car_name: "Kia Sportage 2023",            year: 2023, mileage: 22000,  fuel: "Essence",    body: "SUV",     color: "Blanc",        condition: "Comme neuf", price: 24800, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Kia_Sportage_%28NQ5%29_1X7A0319.jpg/960px-Kia_Sportage_%28NQ5%29_1X7A0319.jpg", description: "Sportage dernière génération, encore sous garantie Kia. Écran 12'', caméra 360, toit panoramique.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-5",  car_name: "Hyundai Tucson 2022",          year: 2022, mileage: 35000,  fuel: "Essence",    body: "SUV",     color: "Rouge",        condition: "Très bon état", price: 23500, ai: "nego", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/2021_Hyundai_Tucson_Elite_N-Line_front.jpg/960px-2021_Hyundai_Tucson_Elite_N-Line_front.jpg", description: "Tucson bien équipé : sièges chauffants, CarPlay, régulateur adaptatif. Historique d'entretien complet.", dealer: { name: "Mukoma Auto", verified: true } },
  { id: "demo-6",  car_name: "Mercedes GLE 400 2021",        year: 2021, mileage: 55000,  fuel: "Essence",    body: "SUV",     color: "Noir obsidienne", condition: "Excellent état", price: 52000, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/2023_Mercedes-AMG_GLE_63_S_4MATIC_IMG_9842_%28cropped%29.jpg/960px-2023_Mercedes-AMG_GLE_63_S_4MATIC_IMG_9842_%28cropped%29.jpg", description: "GLE 400 AMG Line, intérieur cuir beige, suspension pneumatique. Véhicule GCC, jamais importé d'ailleurs.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-7",  car_name: "Nissan Patrol Platinum 2022",  year: 2022, mileage: 46000,  fuel: "Essence",    body: "SUV",     color: "Blanc",        condition: "Excellent état", price: 61500, ai: "nego", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/NISSAN_PATROL_Y62_China_%2816%29.jpg/960px-NISSAN_PATROL_Y62_China_%2816%29.jpg", description: "Patrol Platinum V8, le roi du désert et des grandes familles. 7 places, full options.", dealer: { name: "Al Manara Motors", verified: true } },
  { id: "demo-8",  car_name: "Toyota Prado 2019",            year: 2019, mileage: 105000, fuel: "Diesel",     body: "SUV",     color: "Gris métallisé", condition: "Bon état", price: 29800, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/2022_Toyota_Land_Cruiser_Prado_150_4.0_VX_V6_in_Gray_Metallic%2C_06-12-2024.jpg/960px-2022_Toyota_Land_Cruiser_Prado_150_4.0_VX_V6_in_Gray_Metallic%2C_06-12-2024.jpg", description: "Prado TXL diesel 7 places, increvable. Pneus neufs, révision faite avant mise en vente.", dealer: { name: "Mukoma Auto", verified: true } },
  { id: "demo-9",  car_name: "Honda CR-V 2021",              year: 2021, mileage: 62000,  fuel: "Essence",    body: "SUV",     color: "Blanc",        condition: "Très bon état", price: 22400, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/b/bb/2021_Honda_CR-V_SE_4x2_CVT.jpg", description: "CR-V spacieux et économique, un seul propriétaire. Coffre géant, parfait pour la famille.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-10", car_name: "Mitsubishi Pajero Sport 2018", year: 2018, mileage: 128000, fuel: "Diesel",     body: "SUV",     color: "Gris argent",  condition: "Bon état", price: 18900, ai: "nego", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Mitsubishi_Pajero_Sport_%283rd_generation%29_1X7A0409.jpg/960px-Mitsubishi_Pajero_Sport_%283rd_generation%29_1X7A0409.jpg", description: "Pajero diesel 4x4, robuste et simple à entretenir. Le meilleur rapport qualité-prix pour débuter.", dealer: { name: "Mukoma Auto", verified: true } },
  { id: "demo-11", car_name: "Lexus RX 350 2020",            year: 2020, mileage: 71000,  fuel: "Essence",    body: "SUV",     color: "Blanc nacré",  condition: "Excellent état", price: 42000, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lexus_RX_350_L_FL_1X7A0345.jpg/960px-Lexus_RX_350_L_FL_1X7A0345.jpg", description: "RX 350 luxe et fiabilité Toyota. Intérieur cuir impeccable, aucun frais à prévoir.", dealer: { name: "Al Manara Motors", verified: true } },
  { id: "demo-12", car_name: "Hyundai Kona Électrique 2023", year: 2023, mileage: 12000,  fuel: "Électrique", body: "SUV",     color: "Rouge",        condition: "Comme neuf", price: 26900, ai: "good", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Geneva_International_Motor_Show_2018%2C_Le_Grand-Saconnex_%281X7A1439%29.jpg/960px-Geneva_International_Motor_Show_2018%2C_Le_Grand-Saconnex_%281X7A1439%29.jpg", description: "Kona 100% électrique, 480 km d'autonomie. Zéro carburant, entretien minimal.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-13", car_name: "Toyota Corolla 2022",          year: 2022, mileage: 38000,  fuel: "Essence",    body: "Berline", color: "Blanc",        condition: "Très bon état", price: 17800, ai: "good", photo_url: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=640&q=70", description: "Corolla, la berline la plus fiable au monde. Consommation minime, idéale taxi ou usage quotidien.", dealer: { name: "Kabeya Auto", verified: true } },
  { id: "demo-14", car_name: "Mercedes C200 2021",           year: 2021, mileage: 49000,  fuel: "Essence",    body: "Berline", color: "Noir",         condition: "Excellent état", price: 33500, ai: "nego", photo_url: "https://images.unsplash.com/photo-1625690096555-a0a4d190901c?w=640&q=70", description: "C200 AMG Line, élégance et confort. Véhicule GCC entretenu chez Mercedes Dubai.", dealer: { name: "Al Manara Motors", verified: true } },
  { id: "demo-15", car_name: "Toyota Hiace 2021",            year: 2021, mileage: 88000,  fuel: "Diesel",     body: "Minibus", color: "Blanc",        condition: "Très bon état", price: 25400, ai: "good", photo_url: "https://images.unsplash.com/photo-1650807486050-a142ea418b19?w=640&q=70", description: "Hiace 15 places diesel, la machine à revenus : transport en commun, navettes, livraisons.", dealer: { name: "Mukoma Auto", verified: true } }
];
